To Do list: Second step
pepedropo1/Todo-list pull request #2
Opened 2022-01-12 22:46 UTC by pepedropo1

- Removed all hardcoded items from the tasks array.
- Created a new JavaScript file for the new functionality.
- Implemented a function for adding a new task (add a new element to the array).
- Implemented a function for deleting a task (remove an element from the array).
- Implemented a function for editing task descriptions.
- By default new tasks should have the property completed set to false and the property index set to the value of the new array - length (i.e. if you're adding a 5th task to the list, the index of that task should equal to 5).
- Deleting a task should update all remaining items' indexes, so they represent the current list order and are unique.
- All changes to the To Do List should be saved in local storage.

2022-01-12 22:55 UTC, pepedropo1 commented
Hi! How do I fix eslint linter error "Dependency cycle detected import/no-cycle"?

2022-01-12 23:06 UTC, elisha2kyakpo1 requested changes
Hi @pepedropo1, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, with failing linters, let's make sure that all linter actions pass before submitting for another review request.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **Does not count** into the code reviews limit._

2022-01-12 23:12 UTC, elisha2kyakpo1 commented
Hi @pepedropo1, one way is to reorganize the code so that you do not depend on the same files from both ends.

2022-01-13 00:28 UTC, TedLivist requested changes
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @pepedropo1,

Good job so far!
✔️ Good documentation
✔️ App is runs correctly
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] Users need to install packages and bundle your app. In your README, kindly add `npm install` and `npm run build` (or `npm start`) as necessary commands for setting up the application locally.

- [ ] _Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-13 00:28 UTC, TedLivist commented on src/modules/taskClass.js
> +  }
- [ ] Take a look at the image below. The **`index`** counts of your tasks start from 0 but they should start from 1. For example the first task should have `index: 1`, second task `index: 2` and so on. Kindly fix this.

  ![pedro-index](https://user-images.githubusercontent.com/36542986/149243635-1090fe1d-d7ef-4dce-8ba7-504b87db2138.jpg)

2022-01-13 00:28 UTC, TedLivist commented on src/modules/tasks.js
> +}
- [ ] You have implemented your task deleting function. However, I am unable to remove added tasks from your program. Kindly add a button (or icon or element) to your tasks that, when clicked, allows users to delete that particular task from the UI and localStorage.

- [ ] After a task is deleted remember to update the indexes of the items to represent the current list order too.

2022-01-13 00:28 UTC, TedLivist commented on src/modules/tasks.js
> +}
- [ ] I am unable to edit added tasks. When I modify a task, neither the task UI nor the localStorage is updated to reflect the change. Kindly implement your edit of tasks so that it persists on the UI and localStorage.

2022-01-13 06:59 UTC, pepedropo1 commented on src/modules/tasks.js
> +}
Isn't that on the next step of the project? I thought, for now, I only needed to add the function, later I add the interaction, am I wrong?

2022-01-13 06:59 UTC, pepedropo1 commented on src/modules/tasks.js
> +}
Isn't that on the next step of the project? I thought, for now, I only needed to add the function, later I add the interaction, am I wrong?

2022-01-13 10:22 UTC, TedLivist commented on src/modules/tasks.js
> +}
Hey @pepedropo1. You are required to implement these events now. For example, look at the second to last point of your PR summary (which is the same as the project requirements), it apparently suggests that the indexes of the remaining items should be updated after a deletion function has been triggered (point 4).

2022-01-13 18:05 UTC, SajjadAhmad14 approved these changes
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:

### Hi Pedro, 
## Congratulations 🎉 Thank you for implementing all the requirements 🙏
### Please go ahead and merge the branch!

## Happy Coding 👏👏👏
#### Please leave any questions or comments in the PR if you have any doubts or unclarity!
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-01-13 19:25 UTC, merged